### ISSUE TITLE
Feature Request to add option to return package name as well

### ISSUE THREAD

**Issue by ramya-rao-a** [tpng/gopkgs#5]
The Go extension for Visual Studio Code uses `gopkgs` for multiple scenarios and in one of them, it tries to deduce the package name from the import path.
This is successful most of the time, but as you know, the package name is not always the same as the directory name in the import path.

Can `gopkgs` be modified to return the package name along with the package import path?
May be take a flag and return both name and path if the flag is set?

**Comment by dmitshur** [comment]
The [source](https://github.com/tpng/gopkgs/blob/01f44316de4b24a2ec9ce0a792e3de1e1499b018/main.go) for this tool is 95 lines of code (not counting `doc.go`). It currently takes no flags (it doesn't even try to parse flags), and it operates on a filesystem level only. It doesn't try to read any .go files and parse out the package name:

> It aims to provide a faster alternative to `go list all` to list available packages for import.
>
> The difference of `go list all` and `gopkgs` is that `go list all` looks for go packages in your `$GOPATH/src` while `gopkgs` looks in your `$GOPATH/pkg`. As a result of this, only importable packages that have been installed (either by go get or go install) are listed by `gopkgs`.

So implementing this feature request would be a pretty drastic change to the scope and functionality of this tool, IMO.

Given how short and simple it is, have you considered making a dedicated tool for the purposes of vscode-go plugin, or just implementing the functionality within vscode-go itself?

**Comment by ramya-rao-a** [comment]
@shurcooL True, looking at the code now (should have done that before), I see your point as to how this would be a drastic change.

I'll look into a way to get our problem solved in another way.

Thanks!

**Comment by dmitshur** [comment]
No problem. I'm happy to help with this, if you end up needing help or guidance.
