### ISSUE TITLE
Document case when it doesn't work

### ISSUE THREAD

**Issue by AlekSi** [tpng/gopkgs#6]
gopkgs does not work correctly when package directory (equal to last part of import path) is different from package name (from `package` clause). I think that should be documented explicitly, without requiring a reader to make a conclusion from the last paragraph of README.

Related to #3, #5.

**Comment by tpng** [comment]
Could you give me a concrete example where gopkgs does not work so I can update the README accordingly?
I think the import rules have always been that way, where import is based on directory name while usage in code is based on `package xxxx`.
e.g.
Directory `github.com/tpng/example.v1` with `package example` will result in following usage:
```Go
import "github.com/tpng/example.v1"

func main() {
    example.XXX()
}
```
In this case both `go list all` and `gopkgs` returns `github.com/tpng/example.v1` as the import path.
I can explicitly state that `gopkgs` has no way to returns the real package name in the README though.

**Comment by AlekSi** [comment]
Oops, sorry, you are right. I should have had to double-check what I wrote.
